name: CI
on:
  push:
    paths:
      - .github/workflows/ci.yml
      - cmd/**
      - internal/**
      - pkg/**
      - .dockerignore
      - .golangci.yml
      - .gorelease.yml
      - Dockerfile
      - go.mod
      - go.sum
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - cmd/**
      - internal/**
      - pkg/**
      - .dockerignore
      - .golangci.yml
      - .gorelease.yml
      - Dockerfile
      - go.mod
      - go.sum

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Linting
        run: docker build --target lint .

      - name: Go mod tidy check
        run: docker build --target tidy .

      - name: Build test image
        run: docker build --target test -t test-container .

      - name: Run tests in test container
        run: |
          touch coverage.txt
          docker run --rm \
          -v "$(pwd)/coverage.txt:/tmp/gobuild/coverage.txt" \
          test-container

      # We run this here to use the caching of the previous steps
      - name: Build final image
        run: docker build .

  publish:
    needs: [verify]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1.10.0
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set variables
        id: vars
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          if [ "$TAG" != "$GITHUB_REF" ]; then
            echo "istag=1" >> $GITHUB_ENV
            echo "version=$TAG" >> $GITHUB_ENV
            echo "platforms=linux/amd64,linux/386,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/ppc64le,linux/riscv64" >> $GITHUB_ENV
          elif [ "$BRANCH" = "main" ]; then
            echo "version=latest" >> $GITHUB_ENV
            echo "platforms=linux/amd64,linux/386,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/ppc64le,linux/riscv64" >> $GITHUB_ENV
          else
            echo "version=$BRANCH" >> $GITHUB_ENV
            echo "platforms=linux/amd64" >> $GITHUB_ENV
          fi

      - name: Build and push final image
        uses: docker/build-push-action@v3.1.0
        with:
          platforms: ${{ env.platforms }}
          build-args: |
            CREATED=${{ env.created }}
            COMMIT=${{ env.commit }}
            VERSION=${{ env.version }}
          tags: qmcgaw/devtainr:${{ env.version }}
          push: true

      - if: env.istag == '1'
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - if: env.istag == '1'
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          version: latest
          args: release --config .gorelease.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
